name: swag_labs

on: [push]
jobs:
  swag_labs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: Xotabu4/selenoid-github-action@v2
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub